language: python
sudo: false

python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install --upgrade setuptools
  - pip install -e .[test,xcb]

script:
  - python setup.py test
